name: Build geosite.dat
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Set variables
        run: |
          echo "RELEASE_NAME=$(date +%Y-%m-%d)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y-%m-%d)" >> $GITHUB_ENV
        shell: bash

      - name: Download list
        run: mkdir data && curl -o data/antifilter-community https://community.antifilter.download/list/domains.lst

      - name: Build dat file
        run: |
          go run ./ --exportlists=antifilter-community --outputname=geosite.dat

      - name: Generate sha256 hash
        run: |
          sha256sum geosite.dat > geosite.dat.sha256sum

      - name: Move files to publish directory
        run: |
          #mkdir -p publish
          mv ./output/dat/*.dat ./output/dat/*.sha256sum ./publish

      - name: Release and upload assets
        run: |
          gh release create ${{ env.TAG_NAME }} -t ${{ env.RELEASE_NAME }} \
            ./publish/*.dat \
            ./publish/*.dat.sha256sum
        env:
          GITHUB_TOKEN: ${{ github.token }}
